ports:
- port: 19870
  onOpen: open-preview

tasks:
- before: >
    cd /workspace/uiw/
  init: npm install
  command: npm run bootstrap &&
    npm run b:uiw &&
    npm run b:css &&
    npm run type &&
    npm run website

