name: Deploy Website
on:
  push:
    tags: 
      - v*
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: https://registry.npmjs.org/

    - run: npm install
    - run: npm run hoist

    # - run: npm run build
    - run: npm run b:uiw
    - run: npm run b:css
    - run: npm run type

    - run: npm run bundle
    - run: npm run coverage
    - run: |
        git fetch
        git checkout master
        git branch -a
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        COMMIT=released-${VERSION}
 
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        echo "version: $VERSION"

        node node_modules/.bin/lerna version $VERSION --no-changelog --no-git-tag-version --no-push --yes --force-publish
        npm run b:website
        npm run b:doc
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .

        git commit -am $COMMIT

    - name: git push master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: npm publish
      run: npm run u:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Deploy to uiwjs.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN_UIW }}
        publish_dir: ./website/uiw/build
        publish_branch: master
        external_repository: uiwjs/uiwjs.github.io

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./website/uiw/build
        cname: uiw.js.cool

    - name: Sync to Gitee
      run: |
        mirror() {
          git clone "https://github.com/$1/$2"
          cd "$2"
          git remote add gitee "https://jaywcjlove:${{ secrets.GITEE_TOKEN }}@gitee.com/uiw/$2.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror uiwjs uiw